package br.com.fiap.inovagab.audit.model;

public enum AuditEventType {
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILURE,
    GUIDELINE_CREATED,
    GUIDELINE_UPDATED,
    GUIDELINE_ARCHIVED,
    GUIDELINE_DELETED,
    IDEA_CREATED,
    IDEA_UPDATED,
    IDEA_PRIORITIZED,
    IDEA_APPROVED,
    IDEA_REJECTED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_STATUS_CHANGED,
    AI_ANALYSIS_REQUESTED,
    AI_ANALYSIS_COMPLETED,
    AI_ANALYSIS_FAILED
}

