spring:
  application:
    name: inovagab-api

  profiles:
    default: local
  data:
    mongodb:
      auto-index-creation: false

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never
